services:
  practica-final-xai-api:
    image: elenaardura/practica-final-xai-api
    container_name: practica-final-xai-api
    ports:
    - "5000:5000"
    restart: always

  practica-final-xai-web:
    image: elenaardura/practica-final-xai-web
    container_name: practica-final-xai-web
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://practica-final-xai-api:5000/predict
    depends_on:
      - practica-final-xai-api
    restart: always